<?php

/**
 * BaseTeam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email1
 * @property string $email2
 * @property string $email3
 * @property string $email4
 * @property string $email5
 * @property integer $dm_media_id
 * @property integer $dm_user_id
 * @property boolean $is_active
 * @property DmUser $DmUser
 * @property DmMedia $DmMedia
 * @property Doctrine_Collection $Quests
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getEmail1()      Returns the current record's "email1" value
 * @method string              getEmail2()      Returns the current record's "email2" value
 * @method string              getEmail3()      Returns the current record's "email3" value
 * @method string              getEmail4()      Returns the current record's "email4" value
 * @method string              getEmail5()      Returns the current record's "email5" value
 * @method integer             getDmMediaId()   Returns the current record's "dm_media_id" value
 * @method integer             getDmUserId()    Returns the current record's "dm_user_id" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method DmUser              getDmUser()      Returns the current record's "DmUser" value
 * @method DmMedia             getDmMedia()     Returns the current record's "DmMedia" value
 * @method Doctrine_Collection getQuests()      Returns the current record's "Quests" collection
 * @method Team                setName()        Sets the current record's "name" value
 * @method Team                setEmail1()      Sets the current record's "email1" value
 * @method Team                setEmail2()      Sets the current record's "email2" value
 * @method Team                setEmail3()      Sets the current record's "email3" value
 * @method Team                setEmail4()      Sets the current record's "email4" value
 * @method Team                setEmail5()      Sets the current record's "email5" value
 * @method Team                setDmMediaId()   Sets the current record's "dm_media_id" value
 * @method Team                setDmUserId()    Sets the current record's "dm_user_id" value
 * @method Team                setIsActive()    Sets the current record's "is_active" value
 * @method Team                setDmUser()      Sets the current record's "DmUser" value
 * @method Team                setDmMedia()     Sets the current record's "DmMedia" value
 * @method Team                setQuests()      Sets the current record's "Quests" collection
 * 
 * @package    bquest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTeam extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('team');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email1', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email3', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email4', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email5', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('dm_media_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dm_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DmUser', array(
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('DmMedia', array(
             'local' => 'dm_media_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('Quest as Quests', array(
             'local' => 'id',
             'foreign' => 'team_id'));
    }
}