<?php

/**
 * BaseQuest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property string $deadline
 * @property integer $agency_id
 * @property integer $team_id
 * @property integer $dm_media_id
 * @property integer $theme
 * @property integer $help_type
 * @property integer $hours
 * @property integer $rating
 * @property clob $report_text
 * @property integer $report_image_id
 * @property integer $status
 * @property string $address
 * @property string $latlng
 * @property string $video_url
 * @property string $photo_url
 * @property boolean $is_active
 * @property Agency $Agency
 * @property Team $Team
 * @property DmMedia $DmMedia
 * @property DmMedia $ReportImage
 * 
 * @method string  getName()            Returns the current record's "name" value
 * @method clob    getDescription()     Returns the current record's "description" value
 * @method string  getDeadline()        Returns the current record's "deadline" value
 * @method integer getAgencyId()        Returns the current record's "agency_id" value
 * @method integer getTeamId()          Returns the current record's "team_id" value
 * @method integer getDmMediaId()       Returns the current record's "dm_media_id" value
 * @method integer getTheme()           Returns the current record's "theme" value
 * @method integer getHelpType()        Returns the current record's "help_type" value
 * @method integer getHours()           Returns the current record's "hours" value
 * @method integer getRating()          Returns the current record's "rating" value
 * @method clob    getReportText()      Returns the current record's "report_text" value
 * @method integer getReportImageId()   Returns the current record's "report_image_id" value
 * @method integer getStatus()          Returns the current record's "status" value
 * @method string  getAddress()         Returns the current record's "address" value
 * @method string  getLatlng()          Returns the current record's "latlng" value
 * @method string  getVideoUrl()        Returns the current record's "video_url" value
 * @method string  getPhotoUrl()        Returns the current record's "photo_url" value
 * @method boolean getIsActive()        Returns the current record's "is_active" value
 * @method Agency  getAgency()          Returns the current record's "Agency" value
 * @method Team    getTeam()            Returns the current record's "Team" value
 * @method DmMedia getDmMedia()         Returns the current record's "DmMedia" value
 * @method DmMedia getReportImage()     Returns the current record's "ReportImage" value
 * @method Quest   setName()            Sets the current record's "name" value
 * @method Quest   setDescription()     Sets the current record's "description" value
 * @method Quest   setDeadline()        Sets the current record's "deadline" value
 * @method Quest   setAgencyId()        Sets the current record's "agency_id" value
 * @method Quest   setTeamId()          Sets the current record's "team_id" value
 * @method Quest   setDmMediaId()       Sets the current record's "dm_media_id" value
 * @method Quest   setTheme()           Sets the current record's "theme" value
 * @method Quest   setHelpType()        Sets the current record's "help_type" value
 * @method Quest   setHours()           Sets the current record's "hours" value
 * @method Quest   setRating()          Sets the current record's "rating" value
 * @method Quest   setReportText()      Sets the current record's "report_text" value
 * @method Quest   setReportImageId()   Sets the current record's "report_image_id" value
 * @method Quest   setStatus()          Sets the current record's "status" value
 * @method Quest   setAddress()         Sets the current record's "address" value
 * @method Quest   setLatlng()          Sets the current record's "latlng" value
 * @method Quest   setVideoUrl()        Sets the current record's "video_url" value
 * @method Quest   setPhotoUrl()        Sets the current record's "photo_url" value
 * @method Quest   setIsActive()        Sets the current record's "is_active" value
 * @method Quest   setAgency()          Sets the current record's "Agency" value
 * @method Quest   setTeam()            Sets the current record's "Team" value
 * @method Quest   setDmMedia()         Sets the current record's "DmMedia" value
 * @method Quest   setReportImage()     Sets the current record's "ReportImage" value
 * 
 * @package    bquest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuest extends myDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quest');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             'extra' => 'ckeditor',
             ));
        $this->hasColumn('deadline', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('agency_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('team_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dm_media_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('theme', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('help_type', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('hours', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('report_text', 'clob', null, array(
             'type' => 'clob',
             'extra' => 'ckeditor',
             ));
        $this->hasColumn('report_image_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('latlng', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('video_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('photo_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Agency', array(
             'local' => 'agency_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Team', array(
             'local' => 'team_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('DmMedia', array(
             'local' => 'dm_media_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('DmMedia as ReportImage', array(
             'local' => 'report_image_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}