<?php

/**
 * AgencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AgencyTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return AgencyTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Agency');
    }
}