<?php

/**
 * Message
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    bquest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Message extends BaseMessage
{

  public function getCreatedString()
  {
    return Util::getShortDate( $this->created_at );
  }

  public function getUpdatedString()
  {
    return Util::getShortDate( $this->updated_at );
  }

  /**
   * @param int $limit
   * @return Message[]|Doctrine_Collection
   */
  public static function getLatests( $limit = 10 )
  {
    return myDoctrineQuery::create()
      ->from( 'Message m' )
      ->where( 'm.is_active = ?', true )
      ->orderBy( 'm.created_at DESC' )
      ->limit( $limit )
      ->execute()
      ;
  }

}
