<?php

/**
 * MessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MessageTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return MessageTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Message');
    }
}