<?php

/**
 * QuestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return QuestTable The table object
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Quest');
    }
}