<?php

/**
 * Quote
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    bquest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Quote extends BaseQuote
{

  /**
   * @return Quote
   */
  public static function getRandom()
  {
    return myDoctrineQuery::create()
      ->from( 'Quote q' )
      ->where( 'q.is_active = ?', true )
      ->orderBy('RAND()')
      ->fetchOne();
  }

}
