<?php

/**
 * DmUser
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    bquest
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class DmUser extends PluginDmUser
{

  const TYPE_AGENCY = 1;
  const TYPE_TEAM   = 2;

  public static $userTypeChoices = array(
    self::TYPE_AGENCY => 'НКО',
    self::TYPE_TEAM   => 'Команда',
  );

  public function isTeam()
  {
    return $this->getUserType() == self::TYPE_TEAM;
  }

  public function isAgency()
  {
    return $this->getUserType() == self::TYPE_AGENCY;
  }

}
