<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('agency', 'agency_dm_user_id_dm_user_id', array(
             'name' => 'agency_dm_user_id_dm_user_id',
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('agency', 'agency_dm_media_id_dm_media_id', array(
             'name' => 'agency_dm_media_id_dm_media_id',
             'local' => 'dm_media_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->createForeignKey('quest', 'quest_agency_id_agency_id', array(
             'name' => 'quest_agency_id_agency_id',
             'local' => 'agency_id',
             'foreign' => 'id',
             'foreignTable' => 'agency',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('quest', 'quest_team_id_team_id', array(
             'name' => 'quest_team_id_team_id',
             'local' => 'team_id',
             'foreign' => 'id',
             'foreignTable' => 'team',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('quest', 'quest_dm_media_id_dm_media_id', array(
             'name' => 'quest_dm_media_id_dm_media_id',
             'local' => 'dm_media_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('quest', 'quest_report_image_id_dm_media_id', array(
             'name' => 'quest_report_image_id_dm_media_id',
             'local' => 'report_image_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('team', 'team_dm_user_id_dm_user_id', array(
             'name' => 'team_dm_user_id_dm_user_id',
             'local' => 'dm_user_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_user',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->createForeignKey('team', 'team_dm_media_id_dm_media_id', array(
             'name' => 'team_dm_media_id_dm_media_id',
             'local' => 'dm_media_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_media',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('agency', 'agency_dm_user_id', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
             ),
             ));
        $this->addIndex('agency', 'agency_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
        $this->addIndex('quest', 'quest_agency_id', array(
             'fields' => 
             array(
              0 => 'agency_id',
             ),
             ));
        $this->addIndex('quest', 'quest_team_id', array(
             'fields' => 
             array(
              0 => 'team_id',
             ),
             ));
        $this->addIndex('quest', 'quest_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
        $this->addIndex('quest', 'quest_report_image_id', array(
             'fields' => 
             array(
              0 => 'report_image_id',
             ),
             ));
        $this->addIndex('team', 'team_dm_user_id', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
             ),
             ));
        $this->addIndex('team', 'team_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('agency', 'agency_dm_user_id_dm_user_id');
        $this->dropForeignKey('agency', 'agency_dm_media_id_dm_media_id');
        $this->dropForeignKey('quest', 'quest_agency_id_agency_id');
        $this->dropForeignKey('quest', 'quest_team_id_team_id');
        $this->dropForeignKey('quest', 'quest_dm_media_id_dm_media_id');
        $this->dropForeignKey('quest', 'quest_report_image_id_dm_media_id');
        $this->dropForeignKey('team', 'team_dm_user_id_dm_user_id');
        $this->dropForeignKey('team', 'team_dm_media_id_dm_media_id');
        $this->removeIndex('agency', 'agency_dm_user_id', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
             ),
             ));
        $this->removeIndex('agency', 'agency_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
        $this->removeIndex('quest', 'quest_agency_id', array(
             'fields' => 
             array(
              0 => 'agency_id',
             ),
             ));
        $this->removeIndex('quest', 'quest_team_id', array(
             'fields' => 
             array(
              0 => 'team_id',
             ),
             ));
        $this->removeIndex('quest', 'quest_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
        $this->removeIndex('quest', 'quest_report_image_id', array(
             'fields' => 
             array(
              0 => 'report_image_id',
             ),
             ));
        $this->removeIndex('team', 'team_dm_user_id', array(
             'fields' => 
             array(
              0 => 'dm_user_id',
             ),
             ));
        $this->removeIndex('team', 'team_dm_media_id', array(
             'fields' => 
             array(
              0 => 'dm_media_id',
             ),
             ));
    }
}