<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('quest', 'address', 'string', '255', array(
             ));
        $this->addColumn('quest', 'latlng', 'string', '255', array(
             ));
        $this->addColumn('quest', 'video_url', 'string', '255', array(
             ));
        $this->addColumn('quest', 'photo_url', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('quest', 'address');
        $this->removeColumn('quest', 'latlng');
        $this->removeColumn('quest', 'video_url');
        $this->removeColumn('quest', 'photo_url');
    }
}