<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('agency', 'is_active', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('team', 'is_active', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('agency', 'is_active');
        $this->removeColumn('team', 'is_active');
    }
}