<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('agency', 'description', 'string', '2048', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('agency', 'description');
    }
}